development:
  adapter: postgresql
  encoding: unicode
  database: products_development
  pool: 5
  username: products
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: products_test
  pool: 5
  username: products
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: products_production
  pool: 5
  username: products
  password:
